#!/usr/bin/env python

import sys
import yaml

prefix = sys.argv [1]

data = yaml.safe_load (sys.stdin)

for key in data:

	value = data [key]

	if isinstance (value, str):

		print "%s_%s=\"%s\"" % (prefix, key, value)

	elif isinstance (value, list):

		print "%s_%s=(" % (prefix, key)

		for item in value:
			print "\t\"%s\"" % item

		print ")"

	elif isinstance (value, dict):

		for item_key in value.keys ():
			item_value = value [item_key]
			print "%s_%s_%s=\"%s\"" % (prefix, key, item_key, item_value)

	else:

		raise Exception ("Don't know what to do with %s of %s" % (key, type (value)))
