#!/bin/bash

set -e

project_dir_relative=$(dirname "$0")
project_dir=$(readlink -f "$project_dir_relative")
basename=$(basename "$0")

cd "$project_dir"

# load config

if ! test -f config/overrides.yml; then exit 0; fi
eval $(misc/yaml-to-bash config <config/overrides.yml)

# mount secrets

for secret in "${config_secrets[@]}"; do

	if grep -q "^encfs $project_dir/security/$secret-plain " /proc/mounts; then
		continue
	fi

	echo "Mounting secrets for $secret"

	encfs \
		"$project_dir/security/$secret-cipher" \
		"$project_dir/security/$secret-plain" \
		-- \
		-o allow_root

done

# fix permissions in secrets

for secret in "${config_secrets[@]}"; do

	chmod -R u=rwX,go= security/$secret-plain

done

# ex: noet ts=4 filetype=bash
