#!/bin/bash

set -e

project_dir_relative=$(dirname "$0")
project_dir=$(readlink -f "$project_dir_relative")
basename=$(basename "$0")

cd "$project_dir"

# check we are bootstrapped

if ! test -r "/etc/fuse.conf"; then
	echo "Not mounting secrets because configuration is not complete" >&2
	exit
fi

# load config

if ! test -f config/overrides.yml; then exit 0; fi
source <(misc/yaml-to-bash config <config/overrides.yml)

# mount secrets

for secret in "${config_secrets[@]}"; do

	if grep -q "^encfs $project_dir/security/$secret-plain " /proc/mounts; then
		continue
	fi

	echo "Mounting secrets for $secret"

	mkdir -p "$project_dir/security/$secret-plain"

	password_file="/vagrant/secret/wistla-$secret-secret"

	if test -f "$password_file"; then

		encfs \
			"$project_dir/security/$secret-cipher" \
			"$project_dir/security/$secret-plain" \
			--stdinpass <"$password_file" \
			-- \
			-o allow_root

	else

		encfs \
			"$project_dir/security/$secret-cipher" \
			"$project_dir/security/$secret-plain" \
			-- \
			-o allow_root

	fi

done

# fix permissions in secrets

for secret in "${config_secrets[@]}"; do

	chmod -R u=rwX,go= security/$secret-plain

done

# ex: noet ts=4 filetype=bash
