#!/bin/bash

# always run as root

if test "$UID" != "0"; then
	exec sudo "$0" "$@"
fi

# don't run from host

# TODO

# load ansible environment

cd /vagrant

source ansible/hacking/env-setup >/dev/null

# run ansible-playbook

exec ansible-playbook \
	--inventory-file inventory \
	--extra-vars @config \
	site.yml \
	"${@}"
