#!/bin/bash

{{ ansible_warning ['#'] }}

trap 'kill -TERM $job_pid' HUP

echo "$(date) Starting"

while true; do

	vmstat \
		--active \
		--unit M \
		--wide \
		10 \
	| awk '{ print strftime ("%Y-%m-%d %H:%M:%S"), $0; fflush (); }' \
	>> /var/log/vmstat.log &

	job_pid=$!

	while true; do

		! wait $job_pid

		wait_result=$?

		case $wait_result in
			(128) continue ;;
			(0|129) break ;;
			(*) exit $wait_result ;;
		esac

	done

	echo "$(date) Restarting due to HUP"

done

# ex: noet ts=4 filetype=sh
