#!/bin/bash

{{ ansible_warning ['#'] }}

#set -e

mkdir -p /var/log/openvpn
exec &>> /var/log/openvpn/$common_name.connect.log

echo "----- $(date)"

route_tables=(
	"{{ cluster_network.routes_admin_a }}"
	"{{ cluster_network.routes_admin_b }}"
	"{{ cluster_network.routes_admin_c }}"
{% if cluster_name != 'ops' %}
	"{{ cluster_network.routes_app_a }}"
	"{{ cluster_network.routes_app_b }}"
	"{{ cluster_network.routes_app_c }}"
	"{{ cluster_network.routes_data_a }}"
	"{{ cluster_network.routes_data_b }}"
	"{{ cluster_network.routes_data_c }}"
{% endif %}
{% if cluster_name == 'ops' %}
	"{{ cluster_network.routes_jenkins_a }}"
	"{{ cluster_network.routes_jenkins_b }}"
	"{{ cluster_network.routes_jenkins_c }}"
{% endif %}
)

case "$common_name" in

{% for vpn_client in vpn_clients %}

({{ vpn_client.name }})

{% for iroute in vpn_client.iroutes %}

	ip route replace \
		"{{ iroute.network }}/{{ iroute.netbits }}" \
		via "{{ vpn_network }}.{{ vpn_client.vpn_ip }}"

	for route_table in "${route_tables[@]}"; do

		aws ec2 delete-route \
			--region "{{ cluster.amazon_region }}" \
			--route-table-id "$route_table" \
			--destination-cidr-block "{{ iroute.network }}/{{ iroute.netbits }}" \
		|| true

		aws ec2 create-route \
			--region "{{ cluster.amazon_region }}" \
			--route-table-id "$route_table" \
			--destination-cidr-block "{{ iroute.network }}/{{ iroute.netbits }}" \
			--instance-id "{{ instance_id }}"

	done

{% endfor %}

	true

	;;

{% endfor %}

(wistla-*-admin-*)

	;;

(*)

	echo "Common name not recognised: $common_name" >&2

	exit 1

	;;

esac
