#!/bin/bash

set -e

# nat postrouting

iptables \
	--table nat \
	--flush POSTROUTING

iptables \
	--table nat \
	--policy POSTROUTING ACCEPT

iptables \
	--table nat \
	--append POSTROUTING \
	--source {{ deployment.bridge_network }}/16 \
	--destination 172.16/12 \
	--jump ACCEPT

iptables \
	--table nat \
	--append POSTROUTING \
	--source {{ deployment.bridge_network }}/16 \
	--destination 10/8 \
	--jump ACCEPT

iptables \
	--table nat \
	--append POSTROUTING \
	--source {{ deployment.bridge_network }}/16 \
	--jump MASQUERADE

# ex: noet ts=4 filetype=bash
