#!/bin/bash

set -e

mkdir -p /var/log/openvpn
exec &> /var/log/openvpn/$common_name.disconnect.log

case "$common_name" in

{% for vpn_client in vpn_clients %}

({{ vpn_client.name }})

{% for iroute in vpn_client.iroutes %}

	ip route flush \
		{{ iroute.network }}/{{ iroute.netbits }} \
		via {{ cluster_vpn }}.{{ vpn_groups [zon] }}.{{ vpn_client.vpn_ip }}

{% endfor %}

	;;

{% endfor %}

(*)

	echo "Common name not recognised: $common_name" >&2

	exit 1

	;;

esac
