#!/bin/bash

set -e

# nat prerouting

	# defaults

		iptables \
			--table nat \
			--flush PREROUTING

		iptables \
			--table nat \
			--policy PREROUTING ACCEPT

	# external access to node debugger

		{% if debug | default ('no') == 'yes' %}

		iptables \
			--table nat \
			--append PREROUTING \
			--in-interface eth0 \
			--protocol tcp \
			--dport 8080 \
			--jump DNAT \
			--to-destination 127.0.0.1:8080

		{% endif %}

# ex: noet ts=4 filetype=bash
