#!/bin/sh

{{ ansible_warning ['#'] }}

set -e

exec 1>&2

# if it's not a nodejs project, then, get the fuck out!

if [ ! -f './package.json' ]; then
	exit 0;
fi

current_build_number=`node -e "console.log(parseInt(require('./package.json').wistla.build_number, 10))"`;

new_build_number=`git rev-list HEAD --count`;

# check if build number needs updating

if [[ $current_build_number -eq $new_build_number || $current_build_number -eq $(expr $new_build_number - 1) ]]; then
	# nope: done
	exit 0;
fi

# yesh: increment it

npm run inc_build;

git add package.json;

# commit it
git commit package.json -nm "auto-update build_number";

# let 'em know they need to push again

echo "";

echo "The build_number has been automatically updated.";

echo "Please push again. Push-push-push-push it. Push it! P-PUSH IT REAL GOOD!!!";

echo "";

# done, need to push again

exit 1;
