#!/bin/sh

set -e

exec 1>&2

# fix whitespace tool

fix_whitespace () {

	WHITESPACE_SCRIPT='
		s/[ \t\r][ \t\r]*$//;
	'

	temp=`tempfile`

	filenames=$(
		grep -l -P '[ \t\r]+$' "$@"
	)

	for file in $filenames; do

		echo $file

		sed "$SCRIPT" "$file" >$temp || exit 1

		#colordiff -U3 "$file" "$temp"

		mv "$temp" "$file"

	done

}

# parent is head, or empty for new repo

if git rev-parse --verify HEAD >/dev/null 2>&1; then
	against=HEAD
else
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# check filenames

check_non_ascii () {
	test $(
		git diff --cached --name-only --diff-filter=A -z $against \
		| LC_ALL=C tr -d '[ -~]\0' \
		| wc -c
	) != 0
}

allownonascii=$(git config --bool hooks.allownonascii || true)

if [ "$allownonascii" != "true" ] && check_non_ascii; then

	cat <<-EOF
		Error: non-ascii filenames detected
	EOF

	exit 1

fi

# generate documentation

pwd

if test -f package.json -a -d node_modules/apidoc; then

	npm run-script apidoc

	sed --in-place 's/[ \t\r][ \t\r]*$//;' $(find doc -type f)

	git add -A doc

fi

# check whitespace

git diff-index --check --cached $against --

# done

exit 0
