#!/bin/bash

script="$(readlink --canonicalize "$0")"
scripts_dir="$(dirname "$script")"
project_dir="$(dirname "$scripts_dir")"

third_party_paths=(
	"aws-cli"
	"boto"
	"botocore"
	"dateutil"
	"docutils"
	"jmespath"
	"pyasn1"
	"pythonfutures"
	"python-rsa"
	"roman/src"
	"s3transfer"
)

python_path=""

for third_party_path in "${third_party_paths[@]}"; do
	python_path="$python_path:$project_dir/third-party/$third_party_path"
done

export PYTHONPATH="${python_path:1}"

exec "$project_dir/third-party/aws-cli/bin/aws" "$@"

# ex: noet ts=4 filetype=bash
