#!/usr/bin/env python

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals
from __future__ import with_statement

import sys

sys.path.append (
	"third-party/gitdb")

sys.path.append (
	"third-party/gitpython")

sys.path.append (
	"third-party/pyyaml/lib")

sys.path.append (
	"third-party/smmap")

sys.path.append (
	"third-party/wbs-python")

import wbs.project

command = (
	sys.argv [1]
) if len (sys.argv) > 1 else (
	None
)

if command == "pull":

	wbs.project.thirdparty.pull ()

elif command == "build":

	wbs.project.thirdparty.build ()

elif command == "merge":

	wbs.project.thirdparty.merge ()

else:

	map (
		lambda line:
			sys.stderr.write ("".join ([
				line.format (
					name = sys.argv [0]),
				"\n",
			])),
		[
			"",
			"Syntax:",
			"",
			"  {name} pull   Pull all third party libraries",
			"  {name} build  Build all third party libraries",
			"",
		])

# ex: noet ts=4 filetype=python
