#!/bin/bash

{{ ansible_warning ['#'] }}

if test $# -eq 0; then

	exec sudo lxc-attach --name {{ inventory_hostname }} -- \
	sudo --set-home --user ubuntu bash -

elif test $# -eq 1; then

	exec sudo lxc-attach --name {{ inventory_hostname }} -- \
	sudo --set-home --user ubuntu bash -c "$1"

else

	exec sudo lxc-attach --name {{ inventory_hostname }} -- \
	sudo --set-home --user ubuntu "$@"

fi
