#!/bin/bash

set -euf -o pipefail

# search for a ".nodejs-stub-target" link

working_dir="$PWD"

while test ! -h ".nodejs-stub-target" -a "$PWD" != "/"; do
	cd "..";
done

# resolve the link or use the default

if test -h ".nodejs-stub-target"; then

	nodejs_target=$(
		readlink --canonicalize ".nodejs-stub-target"
	)

else

	nodejs_target=$(
		readlink --canonicalize "/opt/node-default"
	)

fi

cd "$working_dir"

# execute the relevant command

command_name=$(
	basename "$0"
)

exec "$nodejs_target/bin/$command_name" "$@"

# ex: noet ts=4 filetype=bash
